/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.personaDAO;
import controlador.logica_ventana;
import controlador.IdiomaManager;
import java.util.ResourceBundle;

/**
 *
 * @author leydi
 */
public class tabla extends javax.swing.JFrame {

    private logica_ventana controlador;
    private ResourceBundle mensajes;

    private void cargarTabla() {
        personaDAO dao = new personaDAO();
        String[][] datos = dao.obtenerDatosTabla();

        // Columnas traducidas dinámicamente
        String[] columnas = {
            IdiomaManager.getTexto("tabla.columna.nombre"),
            IdiomaManager.getTexto("tabla.columna.telefono"),
            IdiomaManager.getTexto("tabla.columna.email")
        };

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(datos, columnas) {
            boolean[] canEdit = new boolean[]{false, false, false};

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        tablaContactos.setModel(modelo);
    }

    public tabla() {
        initComponents();
        mensajes = IdiomaManager.getBundle();
        internacionalizar(); // primero traduce labels y botones
        cargarTabla();
    }

    private void internacionalizar() {
        Contactos.setText(mensajes.getString("ventana.contactos"));
        jLabel1.setText(mensajes.getString("ventana.filtrar"));
        btn_ordenar.setText(mensajes.getString("ventana.ordenar"));
        jMenu1.setText(mensajes.getString("ventana.opciones"));
        chbm_menuPrincipal.setText(mensajes.getString("ventana.regresar"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContactos = new javax.swing.JTable();
        Contactos = new java.awt.Label();
        btn_ordenar = new javax.swing.JButton();
        txt_filtrar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        chbm_menuPrincipal = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        tablaContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Telefeno", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaContactos);

        Contactos.setText("Contactos");

        btn_ordenar.setText("Ordenar");
        btn_ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenarActionPerformed(evt);
            }
        });

        txt_filtrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_filtrarKeyTyped(evt);
            }
        });

        jLabel1.setText("Filtrar");

        jMenu1.setText("Opciones");

        chbm_menuPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        chbm_menuPrincipal.setSelected(true);
        chbm_menuPrincipal.setText("Regresar");
        chbm_menuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbm_menuPrincipalActionPerformed(evt);
            }
        });
        jMenu1.add(chbm_menuPrincipal);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ordenar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Contactos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Contactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ordenar)
                    .addComponent(txt_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        Contactos.getAccessibleContext().setAccessibleName("Contactos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenarActionPerformed
        controlador.ordenarTabla(tablaContactos);
    }//GEN-LAST:event_btn_ordenarActionPerformed

    private void txt_filtrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtrarKeyTyped
        controlador.filtrarTabla(tablaContactos, txt_filtrar.getText());
    }//GEN-LAST:event_txt_filtrarKeyTyped

    private void chbm_menuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbm_menuPrincipalActionPerformed
        if (chbm_menuPrincipal.isSelected()) {
            // Cerrar el JFrame actual
            this.dispose(); // 'this' si estás en el JFrame actual

            // Abrir la ventana principal
            ventana ventanaPrincipal = new ventana();
            ventanaPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_chbm_menuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Contactos;
    private javax.swing.JButton btn_ordenar;
    private javax.swing.JCheckBoxMenuItem chbm_menuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaContactos;
    private javax.swing.JTextField txt_filtrar;
    // End of variables declaration//GEN-END:variables
}
