/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.*;
import controlador.logica_ventana;
import java.util.List;
import javax.swing.JOptionPane;
import controlador.*;
import java.util.Locale;

/**
 *
 * @author leydi
 */
public class ventana extends javax.swing.JFrame {

    private logica_ventana controlador;

    public ventana() {
        initComponents();

        controlador = new logica_ventana(this);
        controlador.cargarContactosEnLista();
        List<persona> listaPersonas = controlador.dao.leerPersonas();
        controlador.actualizarEstadisticas(listaPersonas, lst_estadistica);

        actualizarTextos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_telefono = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        cmb_categoria = new javax.swing.JComboBox<>();
        btn_add = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        txt_buscarpornombre = new javax.swing.JTextField();
        lbl_nombres_busqueda = new javax.swing.JLabel();
        btn_busqueda = new javax.swing.JButton();
        chb_favorito = new javax.swing.JCheckBox();
        pestañas = new javax.swing.JTabbedPane();
        pestaña_contactos = new javax.swing.JScrollPane();
        lst_contactos = new javax.swing.JList<>();
        tablaContactos = new javax.swing.JScrollPane();
        lst_estadistica = new javax.swing.JList<>();
        progresoBarra = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBusqueda = new javax.swing.JMenu();
        chb_tablaContactos = new javax.swing.JCheckBoxMenuItem();
        jMenuIdiomas = new javax.swing.JMenu();
        menu_ingles = new javax.swing.JMenuItem();
        menu_frances = new javax.swing.JMenuItem();
        menu_español = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION DE CONTACTOS");
        setBackground(new java.awt.Color(0, 255, 204));
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(29, 53, 87));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lbl_nombre.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("NOMBRE");

        lbl_telefono.setBackground(new java.awt.Color(255, 255, 255));
        lbl_telefono.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefono.setText("TELEFONO");

        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });

        lbl_email.setBackground(new java.awt.Color(255, 255, 255));
        lbl_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email.setText("EMAIL");

        cmb_categoria.setBackground(new java.awt.Color(255, 255, 255));
        cmb_categoria.setForeground(new java.awt.Color(0, 0, 0));
        cmb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una categoria", "Familia", "Amigo", "Trabajo" }));
        cmb_categoria.setToolTipText("Categoria");

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-usuario (1).png"))); // NOI18N
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMouseClicked(evt);
            }
        });

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo-de-edicion (1).png"))); // NOI18N
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario-menos (1).png"))); // NOI18N
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        lbl_nombres_busqueda.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nombres_busqueda.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombres_busqueda.setText("NOMBRES");

        btn_busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personas.png"))); // NOI18N
        btn_busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_busquedaMouseClicked(evt);
            }
        });

        chb_favorito.setBackground(new java.awt.Color(255, 255, 255));
        chb_favorito.setForeground(new java.awt.Color(255, 255, 255));
        chb_favorito.setText("Favorito");

        pestañas.setBackground(new java.awt.Color(51, 102, 255));

        lst_contactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_contactosMouseClicked(evt);
            }
        });
        pestaña_contactos.setViewportView(lst_contactos);

        pestañas.addTab("Contactos", pestaña_contactos);

        lst_estadistica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_estadisticaMouseClicked(evt);
            }
        });
        tablaContactos.setViewportView(lst_estadistica);

        pestañas.addTab("Estadistica", tablaContactos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(progresoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pestañas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chb_favorito)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_telefono)
                                    .addComponent(txt_nombre)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(lbl_nombres_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_buscarpornombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_telefono)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_email)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cmb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombres_busqueda)
                    .addComponent(txt_buscarpornombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_busqueda)
                    .addComponent(chb_favorito))
                .addGap(8, 8, 8)
                .addComponent(pestañas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(progresoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(29, 53, 87));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenuBusqueda.setText("Busqueda avanzada");

        chb_tablaContactos.setSelected(true);
        chb_tablaContactos.setText("Clasificacion");
        chb_tablaContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_tablaContactosActionPerformed(evt);
            }
        });
        jMenuBusqueda.add(chb_tablaContactos);

        jMenuIdiomas.setText("Idiomas");

        menu_ingles.setText("Ingles");
        menu_ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_inglesActionPerformed(evt);
            }
        });
        jMenuIdiomas.add(menu_ingles);

        menu_frances.setText("Frances");
        menu_frances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_francesActionPerformed(evt);
            }
        });
        jMenuIdiomas.add(menu_frances);

        menu_español.setText("Español");
        menu_español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_españolActionPerformed(evt);
            }
        });
        jMenuIdiomas.add(menu_español);

        jMenuBusqueda.add(jMenuIdiomas);

        jMenuBar1.add(jMenuBusqueda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseClicked
        String nombre = txt_nombre.getText().trim();
        String telefono = txt_telefono.getText().trim();
        String email = txt_email.getText().trim();
        String categoria = cmb_categoria.getSelectedItem().toString().trim();

        if (nombre.isEmpty() || telefono.isEmpty() || email.isEmpty() || categoria.equals("Elija una categoria")) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios y debe seleccionar una categoría.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el teléfono sea solo números
        // Validar formato de email simple
        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.\\w+$")) {
            JOptionPane.showMessageDialog(this, "Ingrese un correo electrónico válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear objeto persona
        persona p = new persona(
                nombre,
                telefono,
                email,
                categoria,
                chb_favorito.isSelected()
        );

        btn_add.addActionListener(e -> {
            controlador.procesarContacto(
                    logica_ventana.Operacion.AGREGAR,
                    -1,
                    txt_nombre.getText(),
                    txt_telefono.getText(),
                    txt_email.getText(),
                    cmb_categoria.getSelectedItem().toString(),
                    chb_favorito.isSelected()
            );
        });
    }//GEN-LAST:event_btn_addMouseClicked

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        // Solo permitir dígitos y borrar (backspace)
        if (!Character.isDigit(c) && c != '\b') {
            evt.consume(); // Ignora el carácter
            // Opcional: mostrar un aviso pequeño
            // JOptionPane.showMessageDialog(null, "Solo se permiten números");
        }

    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed

        btn_modificar.addActionListener(e -> {
            int index = lst_contactos.getSelectedIndex();
            controlador.procesarContacto(
                    logica_ventana.Operacion.MODIFICAR,
                    index,
                    txt_nombre.getText(),
                    txt_telefono.getText(),
                    txt_email.getText(),
                    cmb_categoria.getSelectedItem().toString(),
                    chb_favorito.isSelected()
            );
        });
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        btn_eliminar.addActionListener(e -> {
            int index = lst_contactos.getSelectedIndex();
            if (index == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un contacto para eliminar.");
                return;
            }
            controlador.procesarContacto(
                    logica_ventana.Operacion.ELIMINAR,
                    index,
                    "",
                    "",
                    "",
                    "",
                    false
            );
        });
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void lst_contactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_contactosMouseClicked
        btn_add.setVisible(true);
        btn_modificar.setVisible(true);
        btn_eliminar.setVisible(true);
        int index = lst_contactos.getSelectedIndex();
        if (index >= 0) {
            controlador.cargarDatosContacto(index);
        }
    }//GEN-LAST:event_lst_contactosMouseClicked

    private void chb_tablaContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_tablaContactosActionPerformed
        if (chb_tablaContactos.isSelected()) {
            this.dispose();
            tabla nuevaVentana = new tabla();
            nuevaVentana.setVisible(true);
            nuevaVentana.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_chb_tablaContactosActionPerformed

    private void lst_estadisticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_estadisticaMouseClicked
        btn_add.setVisible(false);
        btn_modificar.setVisible(false);
        btn_eliminar.setVisible(false);
    }//GEN-LAST:event_lst_estadisticaMouseClicked

    private void menu_inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_inglesActionPerformed
        IdiomaManager.cargarIdioma(new Locale("en", "US"));
        actualizarTextos();
    }//GEN-LAST:event_menu_inglesActionPerformed

    private void menu_francesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_francesActionPerformed
        IdiomaManager.cargarIdioma(new Locale("fr", "FR"));
        actualizarTextos();
    }//GEN-LAST:event_menu_francesActionPerformed

    private void menu_españolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_españolActionPerformed
        IdiomaManager.cargarIdioma(new Locale("es", "ES"));
        actualizarTextos();
    }//GEN-LAST:event_menu_españolActionPerformed

    private void btn_busquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_busquedaMouseClicked
        String texto = txt_buscarpornombre.getText();
        controlador.filtrarLista(texto);
    }//GEN-LAST:event_btn_busquedaMouseClicked
    public javax.swing.JList<String> getLst_contactos() {
        return lst_contactos;
    }

    public void actualizarTextos() {
        setTitle(IdiomaManager.getTexto("titulo"));
        jMenuBusqueda.setText(IdiomaManager.getTexto("menu.busqueda"));
        jMenuIdiomas.setText(IdiomaManager.getTexto("menu.idiomas"));
        menu_ingles.setText(IdiomaManager.getTexto("menu.idiomas.ingles"));
        menu_frances.setText(IdiomaManager.getTexto("menu.idiomas.frances"));
        menu_español.setText(IdiomaManager.getTexto("menu.idiomas.espanol"));

        lbl_nombre.setText(IdiomaManager.getTexto("label.nombre"));
        lbl_telefono.setText(IdiomaManager.getTexto("label.telefono"));
        lbl_email.setText(IdiomaManager.getTexto("label.email"));
        chb_favorito.setText(IdiomaManager.getTexto("label.favorito"));
        lbl_nombres_busqueda.setText(IdiomaManager.getTexto("label.nombres.busqueda"));
        cmb_categoria.setToolTipText(IdiomaManager.getTexto("label.categoria"));
        cmb_categoria.removeAllItems();
        cmb_categoria.addItem(IdiomaManager.getTexto("categoria.opcion1"));
        cmb_categoria.addItem(IdiomaManager.getTexto("categoria.opcion2"));
        cmb_categoria.addItem(IdiomaManager.getTexto("categoria.opcion3"));
        cmb_categoria.addItem(IdiomaManager.getTexto("categoria.opcion4"));
        pestañas.setTitleAt(0, IdiomaManager.getTexto("tab.contactos"));
        pestañas.setTitleAt(1, IdiomaManager.getTexto("tab.estadistica"));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_busqueda;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    public javax.swing.JCheckBox chb_favorito;
    private javax.swing.JCheckBoxMenuItem chb_tablaContactos;
    public javax.swing.JComboBox<String> cmb_categoria;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBusqueda;
    private javax.swing.JMenu jMenuIdiomas;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombres_busqueda;
    private javax.swing.JLabel lbl_telefono;
    public javax.swing.JList<String> lst_contactos;
    private javax.swing.JList<String> lst_estadistica;
    private javax.swing.JMenuItem menu_español;
    private javax.swing.JMenuItem menu_frances;
    private javax.swing.JMenuItem menu_ingles;
    private javax.swing.JScrollPane pestaña_contactos;
    private javax.swing.JTabbedPane pestañas;
    public javax.swing.JProgressBar progresoBarra;
    private javax.swing.JScrollPane tablaContactos;
    public javax.swing.JTextField txt_buscarpornombre;
    public javax.swing.JTextField txt_email;
    public javax.swing.JTextField txt_nombre;
    public javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
