
titulo=GESTI\u00d3N DE CONTACTOS
menu.busqueda=Busqueda avanzada
menu.idiomas=Idiomas
menu.idiomas.ingles=Ingl\u00e9s
menu.idiomas.frances=Franc\u00e9s
menu.idiomas.espanol=Espa\u00f1ol
label.nombre=NOMBRES
label.telefono=TELEFONO
label.email=EMAIL
label.categoria=Categor\u00eda
categoria.opcion1=Elija una categor\u00eda
categoria.opcion2=Familia
categoria.opcion3=Amigos
categoria.opcion4=Trabajo
label.nombres.busqueda=Nombre
label.favorito=Favorito
tab.contactos=Contactos
tab.estadistica=Estad\u00edstica

ventana.contactos=Contactos
ventana.filtrar=Filtrar
ventana.ordenar=Ordenar
ventana.opciones=Opciones
ventana.regresar=Regresar
tabla.titulo=Contacts Table
tabla.columna.nombre=Nombre
tabla.columna.telefono=Telefono
tabla.columna.email=Email

